# Generated by Django 5.2.5 on 2026-03-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
