# Generated by Django 5.2.5 on 2026-03-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_receiver_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
